"""initial schema

Revision ID: 919a7b719305
Revises: 
Create Date: 2026-05-20 12:58:15.140388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '919a7b719305'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_acao'), 'audit_log', ['acao'], unique=False)
    op.create_index(op.f('ix_audit_log_entidade'), 'audit_log', ['entidade'], unique=False)
    op.create_index(op.f('ix_audit_log_entidade_id'), 'audit_log', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_index(op.f('ix_audit_log_usuario_id'), 'audit_log', ['usuario_id'], unique=False)
    op.create_table('produtor',
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('propriedade', sa.String(length=160), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtor_cpf'), 'produtor', ['cpf'], unique=True)
    op.create_index(op.f('ix_produtor_email'), 'produtor', ['email'], unique=True)
    op.create_table('animal',
    sa.Column('produtor_id', sa.Uuid(), nullable=False),
    sa.Column('especie', postgresql.ENUM('BOVINO', 'OVINO', 'CAPRINO', name='especie_enum'), nullable=False),
    sa.Column('identificacao', sa.String(length=50), nullable=False),
    sa.Column('sexo', postgresql.ENUM('MACHO', 'FEMEA', name='sexo_enum'), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('raca', sa.String(length=80), nullable=True),
    sa.Column('linhagem', sa.String(length=120), nullable=True),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('dados_geneticos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produtor_id', 'identificacao', name='uq_animal_produtor_identificacao')
    )
    op.create_index(op.f('ix_animal_especie'), 'animal', ['especie'], unique=False)
    op.create_index(op.f('ix_animal_produtor_id'), 'animal', ['produtor_id'], unique=False)
    op.create_table('ciclo_reprodutivo',
    sa.Column('matriz_id', sa.Uuid(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('ATIVO', 'CONCLUIDO_SUCESSO', 'CONCLUIDO_FALHA', name='status_ciclo_enum'), nullable=False),
    sa.Column('parto_data', sa.Date(), nullable=True),
    sa.Column('cria_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cria_id'], ['animal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matriz_id'], ['animal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciclo_reprodutivo_matriz_id'), 'ciclo_reprodutivo', ['matriz_id'], unique=False)
    op.create_table('inseminacao',
    sa.Column('matriz_id', sa.Uuid(), nullable=False),
    sa.Column('reprodutor_id', sa.Uuid(), nullable=True),
    sa.Column('semen_externo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_evento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tecnica', postgresql.ENUM('IATF', 'CONVENCIONAL', 'IA_REPASSE', 'IA_CERVICAL', 'IA_LAPAROSCOPICA', name='tecnica_enum'), nullable=False),
    sa.Column('inseminador', sa.String(length=160), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('resultado_diagnostico', postgresql.ENUM('PRENHE', 'VAZIA', 'AGUARDANDO', name='resultado_diagnostico_enum'), nullable=False),
    sa.Column('data_diagnostico', sa.Date(), nullable=True),
    sa.Column('predicao_prenhez', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('predicao_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modelo_versao', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matriz_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reprodutor_id'], ['animal.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inseminacao_data_evento'), 'inseminacao', ['data_evento'], unique=False)
    op.create_index(op.f('ix_inseminacao_matriz_id'), 'inseminacao', ['matriz_id'], unique=False)
    op.create_index(op.f('ix_inseminacao_reprodutor_id'), 'inseminacao', ['reprodutor_id'], unique=False)
    op.create_table('recomendacao_cruzamento',
    sa.Column('matriz_id', sa.Uuid(), nullable=False),
    sa.Column('reprodutor_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('justificativa', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modelo_versao', sa.String(length=20), nullable=False),
    sa.Column('gerada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['matriz_id'], ['animal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reprodutor_id'], ['animal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendacao_cruzamento_matriz_id'), 'recomendacao_cruzamento', ['matriz_id'], unique=False)
    op.create_index(op.f('ix_recomendacao_cruzamento_reprodutor_id'), 'recomendacao_cruzamento', ['reprodutor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recomendacao_cruzamento_reprodutor_id'), table_name='recomendacao_cruzamento')
    op.drop_index(op.f('ix_recomendacao_cruzamento_matriz_id'), table_name='recomendacao_cruzamento')
    op.drop_table('recomendacao_cruzamento')
    op.drop_index(op.f('ix_inseminacao_reprodutor_id'), table_name='inseminacao')
    op.drop_index(op.f('ix_inseminacao_matriz_id'), table_name='inseminacao')
    op.drop_index(op.f('ix_inseminacao_data_evento'), table_name='inseminacao')
    op.drop_table('inseminacao')
    op.drop_index(op.f('ix_ciclo_reprodutivo_matriz_id'), table_name='ciclo_reprodutivo')
    op.drop_table('ciclo_reprodutivo')
    op.drop_index(op.f('ix_animal_produtor_id'), table_name='animal')
    op.drop_index(op.f('ix_animal_especie'), table_name='animal')
    op.drop_table('animal')
    op.drop_index(op.f('ix_produtor_email'), table_name='produtor')
    op.drop_index(op.f('ix_produtor_cpf'), table_name='produtor')
    op.drop_table('produtor')
    op.drop_index(op.f('ix_audit_log_usuario_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entidade_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entidade'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_acao'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
